import { createSupabaseBrowserClient } from '@/lib/supabase/browser';
import type { AdminArticle } from '@/types/admin';
export type ArticleInput = Omit<AdminArticle,'id'|'createdAt'|'updatedAt'>;
const map=(r:any):AdminArticle=>({id:String(r.id),title:r.title??'',slug:r.slug??'',excerpt:r.excerpt??'',content:r.content??'',coverImage:r.cover_image_url??'',published:r.published===true,createdAt:r.created_at??'',updatedAt:r.updated_at??''});
export async function listAdminArticles(){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {data,error}=await s.from('articles').select('*').order('created_at',{ascending:false}); if(error) throw error; return (data??[]).map(map);}
export async function createArticle(input:ArticleInput){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {error}=await s.from('articles').insert({title:input.title,slug:input.slug,excerpt:input.excerpt,content:input.content,cover_image_url:input.coverImage,published:input.published,published_at:input.published?new Date().toISOString():null}); if(error) throw error;}
export async function updateArticle(id:string,input:ArticleInput){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {error}=await s.from('articles').update({title:input.title,slug:input.slug,excerpt:input.excerpt,content:input.content,cover_image_url:input.coverImage,published:input.published,published_at:input.published?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',id); if(error) throw error;}
export async function deleteArticle(id:string){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {error}=await s.from('articles').delete().eq('id',id); if(error) throw error;}
export async function toggleArticlePublished(id:string,published:boolean){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {error}=await s.from('articles').update({published,published_at:published?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',id); if(error) throw error;}
