import { createSupabaseBrowserClient } from '@/lib/supabase/browser';
import type { AdminProperty } from '@/types/admin';

export type PropertyInput = Omit<AdminProperty, 'id' | 'createdAt' | 'updatedAt' | 'featuredAt'>;

const mapRow = (row: Record<string, any>): AdminProperty => ({
  id: String(row.id), title: row.title ?? '', slug: row.slug ?? '', purpose: row.purpose === 'rent' ? 'rent' : 'sale',
  propertyType: row.property_type ?? '', location: row.location ?? '', price: Number(row.price ?? 0), bedrooms: Number(row.bedrooms ?? 0),
  bathrooms: Number(row.bathrooms ?? 0), area: Number(row.area_size ?? 0), shortDescription: row.short_description ?? '', fullDescription: row.description ?? '',
  coverImage: row.cover_image_url ?? '', galleryImages: Array.isArray(row.gallery_image_urls) ? row.gallery_image_urls : [],
  featured: row.featured === true, published: row.published === true, createdAt: row.created_at ?? '', updatedAt: row.updated_at ?? '', featuredAt: row.featured_at ?? null,
});

export async function listAdminProperties() { const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {data,error}=await s.from('properties').select('*').order('created_at',{ascending:false}); if(error) throw error; return (data??[]).map(mapRow); }
export async function createProperty(input: PropertyInput) { const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const now=new Date().toISOString(); const {data,error}=await s.from('properties').insert({title:input.title,slug:input.slug,purpose:input.purpose,property_type:input.propertyType,location:input.location,price:input.price,bedrooms:input.bedrooms,bathrooms:input.bathrooms,area_size:input.area,short_description:input.shortDescription,description:input.fullDescription,cover_image_url:input.coverImage,gallery_image_urls:input.galleryImages,featured:input.featured,featured_at:input.featured?now:null,published:input.published}).select('*').single(); if(error) throw error; return mapRow(data); }
export async function updateProperty(id:string,input: PropertyInput){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {error}=await s.from('properties').update({title:input.title,slug:input.slug,purpose:input.purpose,property_type:input.propertyType,location:input.location,price:input.price,bedrooms:input.bedrooms,bathrooms:input.bathrooms,area_size:input.area,short_description:input.shortDescription,description:input.fullDescription,cover_image_url:input.coverImage,gallery_image_urls:input.galleryImages,featured:input.featured,featured_at:input.featured?new Date().toISOString():null,published:input.published,updated_at:new Date().toISOString()}).eq('id',id); if(error) throw error;}
export async function deleteProperty(id:string){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {error}=await s.from('properties').delete().eq('id',id); if(error) throw error;}
export async function togglePublished(id:string,published:boolean){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {error}=await s.from('properties').update({published,updated_at:new Date().toISOString()}).eq('id',id); if(error) throw error;}
export async function toggleFeatured(id:string,featured:boolean){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const now=new Date().toISOString(); if(featured){ const {data,error}=await s.from('properties').select('id').eq('featured',true).order('featured_at',{ascending:true,nullsFirst:true}); if(error) throw error; if((data??[]).length>=3){const overflow=(data??[]).slice(0,(data??[]).length-2).map(r=>r.id); if(overflow.length){ const {error:ce}=await s.from('properties').update({featured:false,featured_at:null,updated_at:now}).in('id',overflow); if(ce) throw ce; } }} const {error}=await s.from('properties').update({featured,featured_at:featured?now:null,updated_at:now}).eq('id',id); if(error) throw error;}
