import { createSupabaseBrowserClient } from '@/lib/supabase/browser';
import type { AdminTeamMember } from '@/types/admin';
export type TeamInput = Omit<AdminTeamMember,'id'|'createdAt'|'updatedAt'>;
const map=(r:any):AdminTeamMember=>({id:String(r.id),name:r.name??'',role:r.role??'',bio:r.bio??'',image:r.image_url??'',email:r.email??undefined,phone:r.phone??undefined,published:r.published===true,createdAt:r.created_at??'',updatedAt:r.updated_at??''});
export async function listAdminTeamMembers(){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {data,error}=await s.from('team_members').select('*').order('created_at',{ascending:false}); if(error) throw error; return (data??[]).map(map);}
export async function createTeamMember(input:TeamInput){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {error}=await s.from('team_members').insert({name:input.name,role:input.role,bio:input.bio,image_url:input.image,email:input.email??null,phone:input.phone??null,published:input.published}); if(error) throw error;}
export async function updateTeamMember(id:string,input:TeamInput){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {error}=await s.from('team_members').update({name:input.name,role:input.role,bio:input.bio,image_url:input.image,email:input.email??null,phone:input.phone??null,published:input.published,updated_at:new Date().toISOString()}).eq('id',id); if(error) throw error;}
export async function deleteTeamMember(id:string){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {error}=await s.from('team_members').delete().eq('id',id); if(error) throw error;}
export async function toggleTeamMemberPublished(id:string,published:boolean){const s=createSupabaseBrowserClient(); if(!s) throw new Error('Supabase not configured'); const {error}=await s.from('team_members').update({published,updated_at:new Date().toISOString()}).eq('id',id); if(error) throw error;}
